CREATE TABLE `alerts` (
  `id` int(11) NOT NULL,
  `alert_type` enum('sms','email') NOT NULL,
  `recipient` varchar(255) NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `message` text NOT NULL,
  `status` enum('pending','sending','sent','failed') DEFAULT 'pending',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `sent_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `brand` (
  `brand_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `brand_name` varchar(250) NOT NULL,
  `brand_status` enum('active','inactive') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `capa_corrective_actions` (
  `action_id` int(11) NOT NULL,
  `capa_uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `recommendation` text COLLATE utf8_unicode_ci NOT NULL,
  `responsible_person` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `target_date` date DEFAULT NULL,
  `status` enum('Open','Completed','Verified') COLLATE utf8_unicode_ci DEFAULT 'Open',
  `created_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `capa_effectiveness` (
  `effectiveness_id` int(11) NOT NULL,
  `capa_uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `corrective_action_id` int(11) DEFAULT NULL,
  `effectiveness_measurement` text COLLATE utf8_unicode_ci,
  `verification_date` date DEFAULT NULL,
  `verified_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` enum('Open','Closed') COLLATE utf8_unicode_ci DEFAULT 'Open',
  `created_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `capa_entries` (
  `capa_id` int(11) NOT NULL,
  `reference_no` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `client` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `reported_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `department` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `designation` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date_reported` datetime NOT NULL,
  `investigation_date` date NOT NULL,
  `incident_type` enum('accident','incident') COLLATE utf8_unicode_ci NOT NULL,
  `event_description` text COLLATE utf8_unicode_ci NOT NULL,
  `immediate_actions` text COLLATE utf8_unicode_ci NOT NULL,
  `root_cause_analysis` text COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('Open','In Progress','Closed') COLLATE utf8_unicode_ci DEFAULT 'Open',
  `created_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_date` datetime NOT NULL,
  `uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `immediate_responsible` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `capa_photos` (
  `photo_id` int(11) NOT NULL,
  `capa_uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `date_uploaded` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `capa_signatures` (
  `signature_id` int(11) NOT NULL,
  `capa_uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `signatory_type` enum('reported_by','investigator','approver') COLLATE utf8_unicode_ci NOT NULL,
  `signatory_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `signature_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `signed_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `category` (
  `category_id` int(11) NOT NULL,
  `category_name` varchar(250) NOT NULL,
  `category_status` enum('active','inactive') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `cleaning_checklist` (
  `id` int(11) NOT NULL,
  `uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `checklist_date` date NOT NULL,
  `checklist_time` time NOT NULL,
  `cleaned_area` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `supervisor` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `supervisor_comment` text COLLATE utf8_unicode_ci,
  `supervisor_signature` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `supervisor_signed_by` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `supervisor_signed_date` datetime DEFAULT NULL,
  `responsible_supervisor` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `responsible_supervisor_signature` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `responsible_supervisor_signed_by` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `responsible_supervisor_signed_date` datetime DEFAULT NULL,
  `created_by` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `created_date` datetime NOT NULL,
  `status` varchar(50) COLLATE utf8_unicode_ci DEFAULT 'Pending Signatures'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `compressors` (
  `compressor_id` int(11) NOT NULL,
  `site` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `month` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `equipment_no` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `location` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `responsible_person` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `week1_status` enum('OK','ISSUES') COLLATE utf8_unicode_ci DEFAULT 'OK',
  `week1_issues` text COLLATE utf8_unicode_ci,
  `week2_status` enum('OK','ISSUES') COLLATE utf8_unicode_ci DEFAULT 'OK',
  `week2_issues` text COLLATE utf8_unicode_ci,
  `week3_status` enum('OK','ISSUES') COLLATE utf8_unicode_ci DEFAULT 'OK',
  `week3_issues` text COLLATE utf8_unicode_ci,
  `week4_status` enum('OK','ISSUES') COLLATE utf8_unicode_ci DEFAULT 'OK',
  `week4_issues` text COLLATE utf8_unicode_ci,
  `week5_status` enum('OK','ISSUES') COLLATE utf8_unicode_ci DEFAULT 'OK',
  `week5_issues` text COLLATE utf8_unicode_ci,
  `corrective_action` text COLLATE utf8_unicode_ci,
  `inspector` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspection_date` datetime DEFAULT NULL,
  `user` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `compressor_photos` (
  `photo_id` int(11) NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `compressor_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `daily_log` (
  `log_id` int(11) NOT NULL,
  `vehicle_id` text NOT NULL,
  `driver` text NOT NULL,
  `odometer_out` text NOT NULL,
  `odometer_in` text NOT NULL,
  `pic_out` text NOT NULL,
  `pic_in` text NOT NULL,
  `date_in` text NOT NULL,
  `date_out` text NOT NULL,
  `date_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dsti_entries` (
  `dsti_id` int(11) NOT NULL,
  `site` varchar(255) NOT NULL,
  `project` varchar(255) NOT NULL,
  `responsible_person` text NOT NULL,
  `week_no` int(11) NOT NULL,
  `safety_checks` longtext NOT NULL,
  `corrective_action` text,
  `inspector_signature` varchar(500) DEFAULT NULL,
  `inspector_name` varchar(255) NOT NULL,
  `inspection_date` datetime NOT NULL,
  `uuid` varchar(255) NOT NULL,
  `status` varchar(50) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dsti_photos` (
  `photo_id` int(11) NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `date` datetime NOT NULL,
  `dsti_id` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `dynamic_form` (
  `uuid` int(11) NOT NULL,
  `name` text CHARACTER SET utf8mb4 NOT NULL,
  `project` text CHARACTER SET utf8mb4 NOT NULL,
  `role` text CHARACTER SET utf8mb4 NOT NULL,
  `phone` int(11) DEFAULT NULL,
  `status` text CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `electrical_equipment` (
  `equipment_id` int(11) NOT NULL,
  `inspection_uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `equipment_location` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `week1` text COLLATE utf8_unicode_ci,
  `week2` text COLLATE utf8_unicode_ci,
  `week3` text COLLATE utf8_unicode_ci,
  `week4` text COLLATE utf8_unicode_ci,
  `week5` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `electrical_inspections` (
  `inspection_id` int(11) NOT NULL,
  `site` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `project` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `responsible_person` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `month` varchar(2) COLLATE utf8_unicode_ci NOT NULL,
  `inspection_date` date NOT NULL,
  `corrective_action` text COLLATE utf8_unicode_ci,
  `uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspector` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `created_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `environment_inspections` (
  `id` int(11) NOT NULL,
  `date` date NOT NULL,
  `auditor` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `area` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `department` varchar(100) COLLATE utf8_unicode_ci DEFAULT 'Technical',
  `doc_no` varchar(50) COLLATE utf8_unicode_ci DEFAULT 'PTL.9.4.1',
  `issue_no` varchar(10) COLLATE utf8_unicode_ci DEFAULT '00',
  `rev_no` varchar(10) COLLATE utf8_unicode_ci DEFAULT '00',
  `overall_score` int(11) DEFAULT NULL,
  `uuid` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` varchar(20) COLLATE utf8_unicode_ci DEFAULT 'Pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `environment_inspection_parameters` (
  `id` int(11) NOT NULL,
  `inspection_id` int(11) DEFAULT NULL,
  `parameter_number` int(11) DEFAULT NULL,
  `parameter_text` text COLLATE utf8_unicode_ci,
  `response` enum('YES','NO') COLLATE utf8_unicode_ci DEFAULT NULL,
  `comments` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `environment_inspection_signatures` (
  `id` int(11) NOT NULL,
  `inspection_id` int(11) DEFAULT NULL,
  `signer_type` enum('auditor','auditee') COLLATE utf8_unicode_ci DEFAULT NULL,
  `signer_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signature_path` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `euser_details` (
  `user_id` int(11) NOT NULL,
  `user_email` varchar(255) NOT NULL,
  `user_password` text NOT NULL,
  `user_name` text NOT NULL,
  `user_team` text,
  `user_type` text NOT NULL,
  `user_status` text NOT NULL,
  `user_location` varchar(255) NOT NULL DEFAULT 'Nairobi',
  `department` text NOT NULL,
  `agent_id` text,
  `driving_license` text NOT NULL,
  `license_date` text NOT NULL,
  `license_expiry` text NOT NULL,
  `date_modified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `phone` text NOT NULL,
  `face_descriptor` text,
  `face_login_enabled` tinyint(1) DEFAULT '0',
  `face_updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `fire_extinguisher_checklist` (
  `id` int(11) NOT NULL,
  `inspection_date` date NOT NULL,
  `team_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `extinguisher_type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `quantity` int(11) NOT NULL,
  `inspection_sticker` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `nozzle` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `gauge` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `handle` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `safety_pin` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `seal` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `remarks` text COLLATE utf8_unicode_ci,
  `inspected_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `user` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` varchar(50) COLLATE utf8_unicode_ci DEFAULT 'Pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `fire_extinguisher_photos` (
  `id` int(11) NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `fire_extinguisher_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `first_aid_inspections` (
  `inspection_id` int(11) NOT NULL,
  `site` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `project` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `responsible_person` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `month` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `equipment_location` text COLLATE utf8_unicode_ci NOT NULL,
  `issues_found` text COLLATE utf8_unicode_ci,
  `corrective_action` text COLLATE utf8_unicode_ci,
  `user` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `map_url` text COLLATE utf8_unicode_ci,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `signature` text COLLATE utf8_unicode_ci,
  `status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `first_aid_photos` (
  `photo_id` int(11) NOT NULL,
  `file_path` text COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `first_aid_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `fuel` (
  `request_id` int(11) NOT NULL,
  `driver` text NOT NULL,
  `vehicle_id` text NOT NULL,
  `amount` text NOT NULL,
  `fuel_station` text NOT NULL,
  `fuel_guage` text NOT NULL,
  `comments` text NOT NULL,
  `approver` text NOT NULL,
  `approval_status` text NOT NULL,
  `approval_date` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `fuel_pics` (
  `photo_id` int(11) NOT NULL,
  `request_id` text NOT NULL,
  `file_path` text NOT NULL,
  `file_name` text NOT NULL,
  `type` text NOT NULL,
  `fuel_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `hse_inspections` (
  `id` int(11) NOT NULL,
  `uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspection_no` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `client` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `project` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `site_location` text COLLATE utf8_unicode_ci,
  `number_of_sites` int(11) DEFAULT NULL,
  `project_duration` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspected_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspection_date` datetime DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` enum('Draft','Completed','In Progress') COLLATE utf8_unicode_ci DEFAULT 'Draft',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `hse_inspection_findings` (
  `id` int(11) NOT NULL,
  `inspection_uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `area` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `finding_description` text COLLATE utf8_unicode_ci,
  `recommended_actions` text COLLATE utf8_unicode_ci,
  `action_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `action_when` date DEFAULT NULL,
  `action_status` enum('Open','In Progress','Completed','Closed') COLLATE utf8_unicode_ci DEFAULT 'Open',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `hse_inspection_photos` (
  `id` int(11) NOT NULL,
  `inspection_uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `finding_id` int(11) DEFAULT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_additional` tinyint(1) DEFAULT '0',
  `upload_date` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspection` (
  `inspection_id` int(11) NOT NULL,
  `vehicle_id` text NOT NULL,
  `driver` text NOT NULL,
  `docs` text NOT NULL,
  `responses` text NOT NULL,
  `comments` text NOT NULL,
  `date_created` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `inspection_photos` (
  `photo_id` int(11) NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `inspection_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `week_number` int(11) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspection_weekly_photos` (
  `weekly_photo_id` int(11) NOT NULL,
  `inspection_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `week_number` int(11) NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `uploaded_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `uploaded_date` datetime NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `inspection_weekly_progress` (
  `progress_id` int(11) NOT NULL,
  `inspection_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `week_number` int(11) DEFAULT NULL,
  `status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `completed_date` datetime DEFAULT NULL,
  `completed_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `insurance` (
  `insurance_id` varchar(255) NOT NULL,
  `insurance` text NOT NULL,
  `date_issued` text NOT NULL,
  `expiry_date` text NOT NULL,
  `vehicle_id` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `jmp` (
  `jmp_id` int(11) NOT NULL,
  `driver_id` int(11) NOT NULL,
  `department` varchar(100) DEFAULT NULL,
  `vehicle_id` text NOT NULL,
  `vehicle_model` varchar(100) DEFAULT NULL,
  `odometer_start` int(11) DEFAULT NULL,
  `fuel_level_start` enum('Full','3/4','1/2','1/4','Almost Empty') DEFAULT NULL,
  `vehicle_condition_check` enum('Yes','No') DEFAULT NULL,
  `journey_date` date NOT NULL,
  `departure_time` time NOT NULL,
  `estimated_return_time` time DEFAULT NULL,
  `origin` varchar(255) NOT NULL,
  `destinations` text NOT NULL,
  `route_planned` text,
  `purpose` text,
  `passengers` int(11) DEFAULT '0',
  `emergency_contact` varchar(100) DEFAULT NULL,
  `emergency_number` varchar(50) DEFAULT NULL,
  `checkin_interval` enum('Hourly','Every 2 hrs','Arrival Only') DEFAULT 'Hourly',
  `tracking_method` varchar(50) DEFAULT NULL,
  `driver_signature` text,
  `acknowledged` tinyint(1) DEFAULT '0',
  `acknowledgement_date` datetime DEFAULT NULL,
  `actual_return_time` time DEFAULT NULL,
  `odometer_end` int(11) DEFAULT NULL,
  `fuel_level_end` enum('Full','3/4','1/2','1/4','Almost Empty') DEFAULT NULL,
  `vehicle_condition_after` text,
  `incidents` text,
  `post_comments` text,
  `approver_id` int(11) DEFAULT NULL,
  `approver_name` varchar(100) DEFAULT NULL,
  `approver_signature` text,
  `approval_comments` text,
  `approval_date` datetime DEFAULT NULL,
  `comments` text,
  `status` enum('Pending','Approved','Completed','Rejected') DEFAULT 'Pending',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `jmp_photos` (
  `photo_id` int(11) NOT NULL,
  `jmp_id` int(11) NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `file_name` varchar(255) NOT NULL,
  `type` varchar(100) DEFAULT NULL,
  `upload_date` datetime DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `jmp_risks` (
  `risk_id` int(11) NOT NULL,
  `jmp_id` int(11) NOT NULL,
  `hazard` varchar(255) NOT NULL,
  `risk_level` enum('Low','Medium','High') NOT NULL,
  `mitigation` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ladder_inspections` (
  `inspection_id` int(11) NOT NULL,
  `project_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `project_location` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `site_details` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `inspection_date` date NOT NULL,
  `equipment_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `general_remarks` text COLLATE utf8_unicode_ci,
  `inspected_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `reviewed_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signatory` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `user` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date_created` datetime NOT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('Pending','Completed','Rejected') COLLATE utf8_unicode_ci DEFAULT 'Pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ladder_inspection_points` (
  `point_id` int(11) NOT NULL,
  `inspection_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `point_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('/','X','N/A') COLLATE utf8_unicode_ci NOT NULL,
  `remarks` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ladder_photos` (
  `photo_id` int(11) NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date` datetime NOT NULL,
  `inspection_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `locations` (
  `location_id` int(11) NOT NULL,
  `location_name` text NOT NULL,
  `location` text NOT NULL,
  `location_status` varchar(255) NOT NULL DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `ppes` (
  `ppe_id` int(11) NOT NULL,
  `user` text COLLATE utf8_unicode_ci NOT NULL,
  `date` text COLLATE utf8_unicode_ci NOT NULL,
  `map_url` text COLLATE utf8_unicode_ci NOT NULL,
  `uuid` text COLLATE utf8_unicode_ci NOT NULL,
  `recipient` text COLLATE utf8_unicode_ci NOT NULL,
  `project` text COLLATE utf8_unicode_ci NOT NULL,
  `item_name` text COLLATE utf8_unicode_ci NOT NULL,
  `quantity` text COLLATE utf8_unicode_ci NOT NULL,
  `unit` text COLLATE utf8_unicode_ci NOT NULL,
  `signature` text COLLATE utf8_unicode_ci NOT NULL,
  `status` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `ppe_photos` (
  `record_id` int(11) NOT NULL,
  `file_path` text COLLATE utf8_unicode_ci NOT NULL,
  `file_name` text COLLATE utf8_unicode_ci NOT NULL,
  `type` text COLLATE utf8_unicode_ci NOT NULL,
  `date` text COLLATE utf8_unicode_ci NOT NULL,
  `ppe_id` text CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `pre_lift_inspections` (
  `id` int(11) NOT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `description_documentation` text COLLATE utf8_unicode_ci,
  `crane_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `crane_inspections_up_to_date` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `crane_preuse_checklist_completed` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `crane_correctly_established` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `crane_barricaded` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `crane_hoist_height` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `crane_slew_radius` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `crane_counter_weight` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `outriggers_extended` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `lifting_equipment_correct` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `lifting_equipment_inspected` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `lifting_equipment_registered` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `tag_lines_inspected` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `slinging_difficulties` text COLLATE utf8_unicode_ci,
  `top_heavy` text COLLATE utf8_unicode_ci,
  `sharp_edges` text COLLATE utf8_unicode_ci,
  `other_hazards` text COLLATE utf8_unicode_ci,
  `overhead_power_lines` text COLLATE utf8_unicode_ci,
  `other_overhead_obstacles` text COLLATE utf8_unicode_ci,
  `underground_services` text COLLATE utf8_unicode_ci,
  `excavations` text COLLATE utf8_unicode_ci,
  `unstable_soft_ground` text COLLATE utf8_unicode_ci,
  `hazardous_chemicals` text COLLATE utf8_unicode_ci,
  `restricted_access_width` text COLLATE utf8_unicode_ci,
  `restricted_access_height` text COLLATE utf8_unicode_ci,
  `other_vehicles_traffic` text COLLATE utf8_unicode_ci,
  `weather_conditions` text COLLATE utf8_unicode_ci,
  `crane_operator_qualified` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `rigger_qualified` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `rigger_assistants_qualified` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `spotters_correctly_placed` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `correct_signage_placed` enum('Yes','No') COLLATE utf8_unicode_ci DEFAULT 'No',
  `site_control` text COLLATE utf8_unicode_ci,
  `additional_comments` text COLLATE utf8_unicode_ci,
  `responsible_rigger_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `responsible_supervisor_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `responsible_rigger_signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `responsible_supervisor_signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` enum('Draft','Completed','Signed') COLLATE utf8_unicode_ci DEFAULT 'Draft',
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `pre_lift_photos` (
  `id` int(11) NOT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `inspection_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `pwdreset` (
  `id` int(11) NOT NULL,
  `email` text NOT NULL,
  `code` text NOT NULL,
  `status` text NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `risk_assessments` (
  `id` int(11) NOT NULL,
  `uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `assessment_no` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `project_activity` text COLLATE utf8_unicode_ci,
  `assessment_date` datetime DEFAULT NULL,
  `facilitator_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `facilitator_signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` enum('Draft','Completed','Reviewed') COLLATE utf8_unicode_ci DEFAULT 'Draft',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `risk_assessment_items` (
  `id` int(11) NOT NULL,
  `assessment_uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `task_activity` text COLLATE utf8_unicode_ci,
  `hazard` text COLLATE utf8_unicode_ci,
  `likelihood` int(11) DEFAULT NULL,
  `severity` int(11) DEFAULT NULL,
  `risk_score` int(11) DEFAULT NULL,
  `risk_rating` enum('Low','Medium','High') COLLATE utf8_unicode_ci DEFAULT NULL,
  `legal_requirement` text COLLATE utf8_unicode_ci,
  `potential_incidents` text COLLATE utf8_unicode_ci,
  `potential_causes` text COLLATE utf8_unicode_ci,
  `controls` text COLLATE utf8_unicode_ci,
  `hierarchy_el` tinyint(1) DEFAULT '0',
  `hierarchy_se` tinyint(1) DEFAULT '0',
  `hierarchy_ad` tinyint(1) DEFAULT '0',
  `hierarchy_su` tinyint(1) DEFAULT '0',
  `hierarchy_re` tinyint(1) DEFAULT '0',
  `hierarchy_ppe` tinyint(1) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `risk_assessment_team` (
  `id` int(11) NOT NULL,
  `assessment_uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `position` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `safety_harness_inspections` (
  `id` int(11) NOT NULL,
  `uuid` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `company` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `year` year(4) DEFAULT NULL,
  `unit_description` enum('Safety belt','Safety harness','Other') COLLATE utf8_unicode_ci DEFAULT NULL,
  `unit_number` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspection_frequency` enum('Monthly','Quarterly','Annually') COLLATE utf8_unicode_ci DEFAULT NULL,
  `designated_person` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspection_date` date DEFAULT NULL,
  `comments` text COLLATE utf8_unicode_ci,
  `findings` text COLLATE utf8_unicode_ci,
  `action_taken` text COLLATE utf8_unicode_ci,
  `action_complete_date` date DEFAULT NULL,
  `status` enum('Pending','Completed','Defective') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `safety_harness_inspection_items` (
  `id` int(11) NOT NULL,
  `inspection_id` int(11) DEFAULT NULL,
  `section` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
  `item_description` text COLLATE utf8_unicode_ci,
  `status` enum('YES','NO','NA') COLLATE utf8_unicode_ci DEFAULT NULL,
  `defect_action` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `safety_harness_signatures` (
  `id` int(11) NOT NULL,
  `inspection_id` int(11) DEFAULT NULL,
  `role` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signature_path` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signed_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `signed_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `service` (
  `service_id` int(11) NOT NULL,
  `vehicle_id` text NOT NULL,
  `driver` text NOT NULL,
  `service_type` text NOT NULL,
  `service_items` text NOT NULL,
  `service_files` text NOT NULL,
  `service_total` text NOT NULL,
  `service_location` text NOT NULL,
  `status` text NOT NULL,
  `approver` text NOT NULL,
  `date` text NOT NULL,
  `comments` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `site_visit_activities` (
  `id` int(11) NOT NULL,
  `report_id` int(11) NOT NULL,
  `activity` text COLLATE utf8_unicode_ci,
  `findings` text COLLATE utf8_unicode_ci,
  `photo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `action_plan` text COLLATE utf8_unicode_ci,
  `recommendation` text COLLATE utf8_unicode_ci,
  `responsible` text COLLATE utf8_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `site_visit_reports` (
  `id` int(11) NOT NULL,
  `report_date` date NOT NULL,
  `site_visited` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `site_visited_by` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `tbts` (
  `tbt_id` int(11) NOT NULL,
  `site_name` text NOT NULL,
  `site_location` text NOT NULL,
  `weather_forecast` text NOT NULL,
  `police` text NOT NULL,
  `hospital` text NOT NULL,
  `activities` text NOT NULL,
  `topic` text NOT NULL,
  `scope` text NOT NULL,
  `comments` text NOT NULL,
  `team` text,
  `user` text NOT NULL,
  `date` datetime NOT NULL,
  `map_url` text NOT NULL,
  `uuid` text NOT NULL,
  `members` text NOT NULL,
  `project` text NOT NULL,
  `team_members` text NOT NULL,
  `team_leader` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `tbt_photos` (
  `record_id` int(11) NOT NULL,
  `file_path` text NOT NULL,
  `file_name` text NOT NULL,
  `type` text NOT NULL,
  `date` datetime NOT NULL,
  `tbt_id` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `teams` (
  `team_id` int(11) NOT NULL,
  `team_name` varchar(255) NOT NULL,
  `location` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'active'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `toolkit` (
  `toolkit_id` int(11) NOT NULL,
  `user` text COLLATE utf8_unicode_ci NOT NULL,
  `date` text COLLATE utf8_unicode_ci NOT NULL,
  `map_url` text COLLATE utf8_unicode_ci NOT NULL,
  `uuid` text COLLATE utf8_unicode_ci NOT NULL,
  `recipient` text COLLATE utf8_unicode_ci NOT NULL,
  `project` text COLLATE utf8_unicode_ci NOT NULL,
  `item_name` text COLLATE utf8_unicode_ci NOT NULL,
  `quantity` text COLLATE utf8_unicode_ci NOT NULL,
  `unit` text COLLATE utf8_unicode_ci NOT NULL,
  `signature` text COLLATE utf8_unicode_ci NOT NULL,
  `status` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `toolkit_photos` (
  `record_id` int(11) NOT NULL,
  `file_path` text COLLATE utf8_unicode_ci NOT NULL,
  `file_name` text COLLATE utf8_unicode_ci NOT NULL,
  `type` text COLLATE utf8_unicode_ci NOT NULL,
  `date` text COLLATE utf8_unicode_ci NOT NULL,
  `toolkit_id` text CHARACTER SET utf8mb4 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `user_details` (
  `user_id` int(11) NOT NULL,
  `user_email` varchar(200) NOT NULL,
  `user_password` varchar(200) NOT NULL,
  `user_name` varchar(200) NOT NULL,
  `user_type` text NOT NULL,
  `user_status` text NOT NULL,
  `user_location` varchar(255) NOT NULL DEFAULT 'Nairobi',
  `location` text NOT NULL,
  `face_descriptor` text,
  `face_login_enabled` tinyint(1) DEFAULT '0',
  `face_updated_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `user_typ` (
  `id` int(11) NOT NULL,
  `type` text NOT NULL,
  `name` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `vehicles` (
  `entry_no` int(11) NOT NULL,
  `vehicle_id` text NOT NULL,
  `registration_no` varchar(255) NOT NULL,
  `make` text NOT NULL,
  `model` text NOT NULL,
  `type` text NOT NULL,
  `color` text NOT NULL,
  `fuel` text NOT NULL,
  `passengers` text NOT NULL,
  `owner_name` text NOT NULL,
  `owner_pin` text NOT NULL,
  `owner_contact` text NOT NULL,
  `logbook` text NOT NULL,
  `driver` text NOT NULL,
  `insurance` text NOT NULL,
  `insurance_date` text NOT NULL,
  `insurance_expiry` text NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'Vaccant',
  `date_created` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vehicle_drivers` (
  `record_id` int(11) NOT NULL,
  `vehicle_id` text NOT NULL,
  `driver_id` int(11) NOT NULL,
  `status` text NOT NULL,
  `date_issued` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `vehicle_inspections` (
  `inspection_id` int(11) NOT NULL,
  `site` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `project` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `vehicle_make` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `vehicle_registration` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `month` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `year` int(11) NOT NULL,
  `responsible_person` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `corrective_action` text COLLATE utf8_unicode_ci,
  `inspector` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `date` datetime NOT NULL,
  `uuid` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `signature` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `current_week` int(11) DEFAULT '1',
  `week_1_status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `week_2_status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `week_3_status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `week_4_status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `week_5_status` enum('Pending','Completed') COLLATE utf8_unicode_ci DEFAULT 'Pending',
  `windscreen_wipers_week1_day1` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `windscreen_wipers_week1_day2` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `windscreen_wipers_week1_day3` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `windscreen_wipers_week1_day4` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `windscreen_wipers_week1_day5` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `windscreen_wipers_week1_day6` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `windscreen_wipers_week1_day7` tinyint(4) DEFAULT '0' COMMENT '0=Not checked, 1=Checked',
  `head_tail_lights_week1_day1` tinyint(4) DEFAULT '0',
  `head_tail_lights_week1_day2` tinyint(4) DEFAULT '0',
  `head_tail_lights_week1_day3` tinyint(4) DEFAULT '0',
  `head_tail_lights_week1_day4` tinyint(4) DEFAULT '0',
  `head_tail_lights_week1_day5` tinyint(4) DEFAULT '0',
  `head_tail_lights_week1_day6` tinyint(4) DEFAULT '0',
  `head_tail_lights_week1_day7` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day1` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day2` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day3` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day4` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day5` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day6` tinyint(4) DEFAULT '0',
  `hooter_horn_week1_day7` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day1` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day2` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day3` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day4` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day5` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day6` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week1_day7` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day1` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day2` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day3` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day4` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day5` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day6` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week1_day7` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day1` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day2` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day3` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day4` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day5` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day6` tinyint(4) DEFAULT '0',
  `brake_lights_week1_day7` tinyint(4) DEFAULT '0',
  `handbrake_week1_day1` tinyint(4) DEFAULT '0',
  `handbrake_week1_day2` tinyint(4) DEFAULT '0',
  `handbrake_week1_day3` tinyint(4) DEFAULT '0',
  `handbrake_week1_day4` tinyint(4) DEFAULT '0',
  `handbrake_week1_day5` tinyint(4) DEFAULT '0',
  `handbrake_week1_day6` tinyint(4) DEFAULT '0',
  `handbrake_week1_day7` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day1` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day2` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day3` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day4` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day5` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day6` tinyint(4) DEFAULT '0',
  `emergency_triangles_week1_day7` tinyint(4) DEFAULT '0',
  `indicators_week1_day1` tinyint(4) DEFAULT '0',
  `indicators_week1_day2` tinyint(4) DEFAULT '0',
  `indicators_week1_day3` tinyint(4) DEFAULT '0',
  `indicators_week1_day4` tinyint(4) DEFAULT '0',
  `indicators_week1_day5` tinyint(4) DEFAULT '0',
  `indicators_week1_day6` tinyint(4) DEFAULT '0',
  `indicators_week1_day7` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day1` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day2` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day3` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day4` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day5` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day6` tinyint(4) DEFAULT '0',
  `radiator_water_week1_day7` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day1` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day2` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day3` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day4` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day5` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day6` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week1_day7` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day1` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day2` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day3` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day4` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day5` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day6` tinyint(4) DEFAULT '0',
  `first_aid_box_week1_day7` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day1` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day2` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day3` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day4` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day5` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day6` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week1_day7` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day1` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day2` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day3` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day4` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day5` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day6` tinyint(4) DEFAULT '0',
  `damage_to_interior_week1_day7` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day1` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day2` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day3` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day4` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day5` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day6` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week1_day7` tinyint(4) DEFAULT '0',
  `other_week1_day1` tinyint(4) DEFAULT '0',
  `other_week1_day2` tinyint(4) DEFAULT '0',
  `other_week1_day3` tinyint(4) DEFAULT '0',
  `other_week1_day4` tinyint(4) DEFAULT '0',
  `other_week1_day5` tinyint(4) DEFAULT '0',
  `other_week1_day6` tinyint(4) DEFAULT '0',
  `other_week1_day7` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day1` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day2` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day3` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day4` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day5` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day6` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week2_day7` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day1` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day2` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day3` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day4` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day5` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day6` tinyint(4) DEFAULT '0',
  `head_tail_lights_week2_day7` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day1` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day2` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day3` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day4` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day5` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day6` tinyint(4) DEFAULT '0',
  `hooter_horn_week2_day7` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day1` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day2` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day3` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day4` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day5` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day6` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week2_day7` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day1` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day2` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day3` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day4` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day5` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day6` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week2_day7` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day1` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day2` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day3` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day4` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day5` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day6` tinyint(4) DEFAULT '0',
  `brake_lights_week2_day7` tinyint(4) DEFAULT '0',
  `handbrake_week2_day1` tinyint(4) DEFAULT '0',
  `handbrake_week2_day2` tinyint(4) DEFAULT '0',
  `handbrake_week2_day3` tinyint(4) DEFAULT '0',
  `handbrake_week2_day4` tinyint(4) DEFAULT '0',
  `handbrake_week2_day5` tinyint(4) DEFAULT '0',
  `handbrake_week2_day6` tinyint(4) DEFAULT '0',
  `handbrake_week2_day7` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day1` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day2` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day3` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day4` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day5` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day6` tinyint(4) DEFAULT '0',
  `emergency_triangles_week2_day7` tinyint(4) DEFAULT '0',
  `indicators_week2_day1` tinyint(4) DEFAULT '0',
  `indicators_week2_day2` tinyint(4) DEFAULT '0',
  `indicators_week2_day3` tinyint(4) DEFAULT '0',
  `indicators_week2_day4` tinyint(4) DEFAULT '0',
  `indicators_week2_day5` tinyint(4) DEFAULT '0',
  `indicators_week2_day6` tinyint(4) DEFAULT '0',
  `indicators_week2_day7` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day1` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day2` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day3` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day4` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day5` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day6` tinyint(4) DEFAULT '0',
  `radiator_water_week2_day7` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day1` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day2` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day3` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day4` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day5` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day6` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week2_day7` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day1` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day2` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day3` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day4` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day5` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day6` tinyint(4) DEFAULT '0',
  `first_aid_box_week2_day7` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day1` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day2` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day3` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day4` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day5` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day6` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week2_day7` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day1` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day2` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day3` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day4` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day5` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day6` tinyint(4) DEFAULT '0',
  `damage_to_interior_week2_day7` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day1` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day2` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day3` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day4` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day5` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day6` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week2_day7` tinyint(4) DEFAULT '0',
  `other_week2_day1` tinyint(4) DEFAULT '0',
  `other_week2_day2` tinyint(4) DEFAULT '0',
  `other_week2_day3` tinyint(4) DEFAULT '0',
  `other_week2_day4` tinyint(4) DEFAULT '0',
  `other_week2_day5` tinyint(4) DEFAULT '0',
  `other_week2_day6` tinyint(4) DEFAULT '0',
  `other_week2_day7` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day1` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day2` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day3` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day4` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day5` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day6` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week3_day7` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day1` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day2` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day3` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day4` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day5` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day6` tinyint(4) DEFAULT '0',
  `head_tail_lights_week3_day7` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day1` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day2` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day3` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day4` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day5` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day6` tinyint(4) DEFAULT '0',
  `hooter_horn_week3_day7` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day1` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day2` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day3` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day4` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day5` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day6` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week3_day7` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day1` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day2` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day3` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day4` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day5` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day6` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week3_day7` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day1` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day2` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day3` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day4` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day5` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day6` tinyint(4) DEFAULT '0',
  `brake_lights_week3_day7` tinyint(4) DEFAULT '0',
  `handbrake_week3_day1` tinyint(4) DEFAULT '0',
  `handbrake_week3_day2` tinyint(4) DEFAULT '0',
  `handbrake_week3_day3` tinyint(4) DEFAULT '0',
  `handbrake_week3_day4` tinyint(4) DEFAULT '0',
  `handbrake_week3_day5` tinyint(4) DEFAULT '0',
  `handbrake_week3_day6` tinyint(4) DEFAULT '0',
  `handbrake_week3_day7` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day1` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day2` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day3` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day4` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day5` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day6` tinyint(4) DEFAULT '0',
  `emergency_triangles_week3_day7` tinyint(4) DEFAULT '0',
  `indicators_week3_day1` tinyint(4) DEFAULT '0',
  `indicators_week3_day2` tinyint(4) DEFAULT '0',
  `indicators_week3_day3` tinyint(4) DEFAULT '0',
  `indicators_week3_day4` tinyint(4) DEFAULT '0',
  `indicators_week3_day5` tinyint(4) DEFAULT '0',
  `indicators_week3_day6` tinyint(4) DEFAULT '0',
  `indicators_week3_day7` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day1` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day2` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day3` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day4` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day5` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day6` tinyint(4) DEFAULT '0',
  `radiator_water_week3_day7` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day1` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day2` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day3` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day4` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day5` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day6` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week3_day7` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day1` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day2` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day3` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day4` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day5` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day6` tinyint(4) DEFAULT '0',
  `first_aid_box_week3_day7` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day1` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day2` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day3` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day4` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day5` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day6` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week3_day7` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day1` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day2` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day3` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day4` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day5` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day6` tinyint(4) DEFAULT '0',
  `damage_to_interior_week3_day7` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day1` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day2` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day3` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day4` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day5` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day6` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week3_day7` tinyint(4) DEFAULT '0',
  `other_week3_day1` tinyint(4) DEFAULT '0',
  `other_week3_day2` tinyint(4) DEFAULT '0',
  `other_week3_day3` tinyint(4) DEFAULT '0',
  `other_week3_day4` tinyint(4) DEFAULT '0',
  `other_week3_day5` tinyint(4) DEFAULT '0',
  `other_week3_day6` tinyint(4) DEFAULT '0',
  `other_week3_day7` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day1` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day2` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day3` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day4` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day5` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day6` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week4_day7` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day1` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day2` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day3` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day4` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day5` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day6` tinyint(4) DEFAULT '0',
  `head_tail_lights_week4_day7` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day1` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day2` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day3` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day4` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day5` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day6` tinyint(4) DEFAULT '0',
  `hooter_horn_week4_day7` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day1` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day2` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day3` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day4` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day5` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day6` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week4_day7` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day1` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day2` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day3` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day4` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day5` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day6` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week4_day7` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day1` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day2` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day3` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day4` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day5` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day6` tinyint(4) DEFAULT '0',
  `brake_lights_week4_day7` tinyint(4) DEFAULT '0',
  `handbrake_week4_day1` tinyint(4) DEFAULT '0',
  `handbrake_week4_day2` tinyint(4) DEFAULT '0',
  `handbrake_week4_day3` tinyint(4) DEFAULT '0',
  `handbrake_week4_day4` tinyint(4) DEFAULT '0',
  `handbrake_week4_day5` tinyint(4) DEFAULT '0',
  `handbrake_week4_day6` tinyint(4) DEFAULT '0',
  `handbrake_week4_day7` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day1` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day2` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day3` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day4` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day5` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day6` tinyint(4) DEFAULT '0',
  `emergency_triangles_week4_day7` tinyint(4) DEFAULT '0',
  `indicators_week4_day1` tinyint(4) DEFAULT '0',
  `indicators_week4_day2` tinyint(4) DEFAULT '0',
  `indicators_week4_day3` tinyint(4) DEFAULT '0',
  `indicators_week4_day4` tinyint(4) DEFAULT '0',
  `indicators_week4_day5` tinyint(4) DEFAULT '0',
  `indicators_week4_day6` tinyint(4) DEFAULT '0',
  `indicators_week4_day7` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day1` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day2` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day3` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day4` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day5` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day6` tinyint(4) DEFAULT '0',
  `radiator_water_week4_day7` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day1` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day2` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day3` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day4` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day5` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day6` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week4_day7` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day1` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day2` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day3` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day4` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day5` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day6` tinyint(4) DEFAULT '0',
  `first_aid_box_week4_day7` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day1` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day2` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day3` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day4` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day5` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day6` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week4_day7` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day1` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day2` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day3` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day4` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day5` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day6` tinyint(4) DEFAULT '0',
  `damage_to_interior_week4_day7` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day1` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day2` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day3` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day4` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day5` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day6` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week4_day7` tinyint(4) DEFAULT '0',
  `other_week4_day1` tinyint(4) DEFAULT '0',
  `other_week4_day2` tinyint(4) DEFAULT '0',
  `other_week4_day3` tinyint(4) DEFAULT '0',
  `other_week4_day4` tinyint(4) DEFAULT '0',
  `other_week4_day5` tinyint(4) DEFAULT '0',
  `other_week4_day6` tinyint(4) DEFAULT '0',
  `other_week4_day7` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day1` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day2` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day3` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day4` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day5` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day6` tinyint(4) DEFAULT '0',
  `windscreen_wipers_week5_day7` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day1` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day2` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day3` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day4` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day5` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day6` tinyint(4) DEFAULT '0',
  `head_tail_lights_week5_day7` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day1` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day2` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day3` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day4` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day5` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day6` tinyint(4) DEFAULT '0',
  `hooter_horn_week5_day7` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day1` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day2` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day3` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day4` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day5` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day6` tinyint(4) DEFAULT '0',
  `tyres_spare_wheel_week5_day7` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day1` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day2` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day3` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day4` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day5` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day6` tinyint(4) DEFAULT '0',
  `jack_wheel_spanner_week5_day7` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day1` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day2` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day3` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day4` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day5` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day6` tinyint(4) DEFAULT '0',
  `brake_lights_week5_day7` tinyint(4) DEFAULT '0',
  `handbrake_week5_day1` tinyint(4) DEFAULT '0',
  `handbrake_week5_day2` tinyint(4) DEFAULT '0',
  `handbrake_week5_day3` tinyint(4) DEFAULT '0',
  `handbrake_week5_day4` tinyint(4) DEFAULT '0',
  `handbrake_week5_day5` tinyint(4) DEFAULT '0',
  `handbrake_week5_day6` tinyint(4) DEFAULT '0',
  `handbrake_week5_day7` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day1` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day2` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day3` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day4` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day5` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day6` tinyint(4) DEFAULT '0',
  `emergency_triangles_week5_day7` tinyint(4) DEFAULT '0',
  `indicators_week5_day1` tinyint(4) DEFAULT '0',
  `indicators_week5_day2` tinyint(4) DEFAULT '0',
  `indicators_week5_day3` tinyint(4) DEFAULT '0',
  `indicators_week5_day4` tinyint(4) DEFAULT '0',
  `indicators_week5_day5` tinyint(4) DEFAULT '0',
  `indicators_week5_day6` tinyint(4) DEFAULT '0',
  `indicators_week5_day7` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day1` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day2` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day3` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day4` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day5` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day6` tinyint(4) DEFAULT '0',
  `radiator_water_week5_day7` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day1` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day2` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day3` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day4` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day5` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day6` tinyint(4) DEFAULT '0',
  `oil_clutch_brake_fluid_week5_day7` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day1` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day2` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day3` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day4` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day5` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day6` tinyint(4) DEFAULT '0',
  `first_aid_box_week5_day7` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day1` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day2` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day3` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day4` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day5` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day6` tinyint(4) DEFAULT '0',
  `fire_extinguisher_week5_day7` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day1` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day2` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day3` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day4` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day5` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day6` tinyint(4) DEFAULT '0',
  `damage_to_interior_week5_day7` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day1` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day2` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day3` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day4` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day5` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day6` tinyint(4) DEFAULT '0',
  `damage_to_exterior_week5_day7` tinyint(4) DEFAULT '0',
  `other_week5_day1` tinyint(4) DEFAULT '0',
  `other_week5_day2` tinyint(4) DEFAULT '0',
  `other_week5_day3` tinyint(4) DEFAULT '0',
  `other_week5_day4` tinyint(4) DEFAULT '0',
  `other_week5_day5` tinyint(4) DEFAULT '0',
  `other_week5_day6` tinyint(4) DEFAULT '0',
  `other_week5_day7` tinyint(4) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='Vehicle Inspection Checklist - All 5 weeks data (560 inspection columns)';

CREATE TABLE `wash_pics` (
  `photo_id` int(11) NOT NULL,
  `request_id` int(11) NOT NULL,
  `file_path` text COLLATE utf8_unicode_ci NOT NULL,
  `file_name` text COLLATE utf8_unicode_ci NOT NULL,
  `type` text COLLATE utf8_unicode_ci NOT NULL,
  `fuel_date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `worktype` (
  `deptid` int(11) NOT NULL,
  `dname` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='eg. installation';

CREATE TABLE `work_permits` (
  `permit_id` int(11) NOT NULL,
  `permit_number` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `permit_type` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `operator_type` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `operator_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `operator_count` int(11) DEFAULT NULL,
  `requested_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `department` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `position` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `valid_from` datetime DEFAULT NULL,
  `valid_to` datetime DEFAULT NULL,
  `work_location` text COLLATE utf8_unicode_ci,
  `work_description` text COLLATE utf8_unicode_ci,
  `tools_equipment` text COLLATE utf8_unicode_ci,
  `risks_hazards` json DEFAULT NULL,
  `safety_requirements` json DEFAULT NULL,
  `ppe_required` json DEFAULT NULL,
  `initiator_signature` text COLLATE utf8_unicode_ci,
  `operator_signature` text COLLATE utf8_unicode_ci,
  `inspector_signature` text COLLATE utf8_unicode_ci,
  `project_manager_signature` text COLLATE utf8_unicode_ci,
  `initiator_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `operator_person` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspector_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inspector` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `project_manager` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `project_manager_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `initiator_signature_date` datetime DEFAULT NULL,
  `operator_signature_date` datetime DEFAULT NULL,
  `inspector_signature_date` datetime DEFAULT NULL,
  `project_manager_signature_date` datetime DEFAULT NULL,
  `other_risks` text COLLATE utf8_unicode_ci,
  `other_safety` text COLLATE utf8_unicode_ci,
  `other_ppe` text COLLATE utf8_unicode_ci,
  `emergency_numbers` json DEFAULT NULL,
  `status` varchar(50) COLLATE utf8_unicode_ci DEFAULT 'Draft',
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `uuid` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `map_url` text COLLATE utf8_unicode_ci,
  `initiator_email` text COLLATE utf8_unicode_ci NOT NULL,
  `initiator_phone` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `work_permit_approvals` (
  `approval_id` int(11) NOT NULL,
  `permit_id` int(11) NOT NULL,
  `approver_type` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `approver_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `approval_date` datetime NOT NULL,
  `status` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT 'Signed',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `work_permit_attachments` (
  `attachment_id` int(11) NOT NULL,
  `work_permit_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `file_path` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `file_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `file_type` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `uploaded_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

