<?php
/* manifest.php — PWA manifest generated by PHP (like the Kennet valuation app), so it always
   deploys with the rest of the PHP files. Paths are relative to this file's URL, which keeps it
   correct whether the app is at the domain root or a subfolder (e.g. /WORKINGCAPITAL/). */
header('Content-Type: application/manifest+json; charset=utf-8');
echo json_encode([
    'name'             => '912 Finance Console',
    'short_name'       => '912',
    'description'      => 'Waitara Holdings Group — finance console',
    'start_url'        => 'index.php',
    'scope'            => './',
    'display'          => 'standalone',
    'orientation'      => 'portrait',
    'background_color' => '#0F1B2D',
    'theme_color'      => '#15202B',
    'icons' => [
        ['src' => 'icon-192.png', 'sizes' => '192x192', 'type' => 'image/png', 'purpose' => 'any'],
        ['src' => 'icon-512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'any'],
        ['src' => 'icon-512.png', 'sizes' => '512x512', 'type' => 'image/png', 'purpose' => 'maskable'],
    ],
], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
